development:
  adapter:  postgresql
  database: tommydangerous_development
  encoding: unicode
  password: postgres
  pool:     5
  timeout:  5000
  username: postgres
production:
  adapter:  postgresql
  database: tommydangerous_production
  encoding: unicode
  host:     tommydangerouspostgresql.clajyggponap.us-west-1.rds.amazonaws.com
  password: postgres
  pool:     5
  port:     5432
  timeout:  5000
  username: postgres
