development:
  adapter: mysql2
  database: tommydangerous_development
  username: root
  pool: 5
  timeout: 5000
production:
  adapter: mysql2
  database: tommydangerous
  host: tommydangerous.clajyggponap.us-west-1.rds.amazonaws.com
  password: quantumventures
  pool: 5
  port: 3306
  timeout: 5000  
